version: '3'
services:
  # jaeger:
  #   container_name: dev_jaeger
  #   image: jaegertracing/all-in-one:1.18
  #   environment:
  #     COLLECTOR_ZIPKIN_HTTP_PORT: 9411
  #   ports:
  #     - "5775:5775/udp"  # agent:      accept zipkin.thrift over compact thrift protocol (deprecated)
  #     - "6831:6831/udp"  # agent:      accept jaeger.thrift over compact thrift protocol
  #     - "6832:6832/udp"  # agent:      accept jaeger.thrift over binary thrift protocol
  #     - "5778:5778"      # agent:      server configs
  #     - "14268:14268"    # collector:  accept jaeger.thrift directly from clients
  #     - "14250:14250"    # collector:  accept model.proto
  #     - "9411:9411"      # collector:  Zipkin compatible endpoint (optional)
  #     - "16686:16686"    # query:      server frontend
  #   networks:
  #     main:
  #       aliases:
  #         - jaeger
  service_one:
    container_name: dev_service_one
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    command: dotnet run -p /ServiceOne
    restart: always
    ports:
      - 8001:8001
    volumes:
      - ./ServiceOne:/ServiceOne
    networks:
      main:
        aliases:
          - service_one
  service_two:
    container_name: dev_service_two
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    command: dotnet run -p /ServiceTwo
    restart: always
    ports:
      - 8002:8002
    volumes:
      - ./ServiceTwo:/ServiceTwo
    networks:
      main:
        aliases:
          - service_two
  service_three:
    container_name: dev_service_three
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    command: dotnet run -p /ServiceThree
    restart: always
    ports:
      - 8003:8003
    volumes:
      - ./ServiceThree:/ServiceThree
    networks:
      main:
        aliases:
          - service_three
  service_four:
    container_name: dev_service_four
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    command: dotnet run -p /ServiceFour
    restart: always
    ports:
      - 8004:8004
    volumes:
      - ./ServiceFour:/ServiceFour
    networks:
      main:
        aliases:
          - service_four
  service_five:
    container_name: dev_service_five
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    command: dotnet run -p /ServiceFive
    restart: always
    ports:
      - 8005:8005
    volumes:
      - ./ServiceFive:/ServiceFive
    networks:
      main:
        aliases:
          - service_five
networks:
  main:

